### ISSUE TITLE
blöcke

### ISSUE THREAD

**Issue by Bubbelwubbel** [note3crafter/CoreV6-API4#1]
Mit welcher World Format Typ gehen die Blöcke? Weil bei leveldb kommen nur diese Verbuggten Blöcke.

**Comment by note3crafter** [comment]
Ehm ganz normal in pmmpapi4

**Comment by Bubbelwubbel** [comment]
Jaja, is Api4 mit leveldb.

**Comment by note3crafter** [comment]
ich nutze ganz normal die api4 nicht anders xD

**Comment by Bubbelwubbel** [comment]
Das ist ja normal API4.

**Comment by note3crafter** [comment]
Gibt es sonnst noch was?

**Comment by supercrafter333** [comment]
Ja, PMAnvil und MCRegion

**Comment by Bubbelwubbel** [comment]
? @supercrafter333

**Comment by supercrafter333** [comment]
Ich meine damit Welt-Formate
