### ISSUE TITLE
EnderChest Command without InvMenu

### ISSUE THREAD

**Issue by supercrafter333** [note3crafter/CoreV6-API4#2]
Mach mal ohne InvMenu, ist besser

**Comment by note3crafter** [comment]
wenn du eine idee hättest xD dann ja ich weis es aktuell nicht wie man es sonnst machen könnte :D

**Comment by supercrafter333** [comment]
Ich habe es bisher so, dass die EC gesetzt wird. Ich arbeite nur noch drann, dass sich das Inventar öffnet.

**Comment by note3crafter** [comment]
naja ist meine sache wie ich es mache... von dir möchte ich keine Hilfe mehr leute die nur am vorurteilen sind möchte ich keinen Kontakt haben ✌️
