### ISSUE TITLE
"TheNote\core\item\Shield" not found"

### ISSUE THREAD

**Issue by Auslatos** [note3crafter/CoreV6-API4#6]
[23:39:41.740] [Server thread/CRITICAL]: Error: "Class "TheNote\core\item\Shield" not found" (EXCEPTION) in "plugins/CoreV6-API4_dev-28.phar/src/TheNote/core/item/ItemManager" at line 82
--- Stack trace ---
  #0 plugins/CoreV6-API4_dev-28.phar/src/TheNote/core/Main(363): TheNote\core\item\ItemManager::init()
  #1 pmsrc/src/plugin/PluginBase(95): TheNote\core\Main->onLoad()
  #2 pmsrc/src/plugin/PluginManager(214): pocketmine\plugin\PluginBase->__construct(object pocketmine\plugin\PharPluginLoader#24869, object pocketmine\Server#10, object pocketmine\plugin\PluginDescription#25217, string[34] /home/container/plugin_data/CoreV6, string[54] phar:///home/container/plugins/CoreV6-API4_dev-28.phar, object pocketmine\plugin\DiskResourceProvider#25943)
  #3 pmsrc/src/plugin/PluginManager(356): pocketmine\plugin\PluginManager->internalLoadPlugin(string[47] /home/container/plugins/CoreV6-API4_dev-28.phar, object pocketmine\plugin\PharPluginLoader#24869, object pocketmine\plugin\PluginDescription#25217)
  #4 pmsrc/src/Server(1005): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/container/plugins/)
  #5 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #6 pmsrc/src/PocketMine(327): pocketmine\server()
  #7 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by note3crafter** [comment]
Fixed...

**Comment by Auslatos** [comment]
InvalidArgumentException: "Block registration 468:0 conflicts with an existing block" (EXCEPTION) in "pmsrc/src/block/BlockFactory" at line 985

**Comment by Auslatos** [comment]
I thinks that a lot of items/block that you added to the core are already in game now (pm4)

**Comment by note3crafter** [comment]
i fix it later

**Comment by note3crafter** [comment]
fixed
