### ISSUE TITLE
Idee 

### ISSUE THREAD

**Issue by GamerMJay** [note3crafter/CoreV6-API4#7]
Hey, meine idee lautet das man mehr in der config aktivieren/deaktivieren kann beispiel das man das Heiraten System deaktivieren kann oder die Perks economy und so halt! Ich denke dann würde CoreV6 mehr genutzt werden. Ich nutze sie leider aktuell auch nicht da ich ein Economy System habe und wenn man in der config Economy deaktivieren kann würde ich sie auch Nutzen!

Mit freundlichen Grüßen @GamerMJay

**Comment by note3crafter** [comment]
Das Economy System wird tatsächlich abgeschaltet sofern Das richtig EconomyAPI drauf ist... Den rest werde ich wenn ich Lust und Zeit habe schauen
